server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&allowMultiQueries=true
    username: root
    password: 123456
  application:
      name: servce
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/


