eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zengcengming/zcm.git
          username: 958846391@qq.com
          password: zeng15070234507
#          basedir: D:\work\file\juejinDome\cloudTest\configBasedir 文件存储地址